### PR TITLE
chore: Fix Cache Mismatch by Deep Copying Operation

### LINKED ISSUE #1310: Retried operations pollute the cache with incorrect values
Given operation A, which failed.
I retried operation A, which created operation B.
Now, when performing a "get one" to get operation A, it actually returns the details of operation B.
When performing a "get many", the details of operation A can be retrieved correctly.

Somehow it seems like the cache became polluted (since the "get one" API goes to the cache). I haven't pinpointed the exact path, but it may be somewhere around this area:
https://github.com/hyperledger/firefly/blob/4df24f30508b046fe57def1d386d2fb73a5d1979/internal/operations/manager.go#L214

### PR DESCRIPTION
**Pull request by dwertent**
Added a deep copy of the operation object to prevent ID overwriting issues. Read more [here](https://github.com/hyperledger/firefly/issues/1310#issuecomment-2297198669).

Fixes #1310

### CODE REVIEW

**Comment by EnriqueL8** [comment]
@awrichar Could you take a look at this one?

File: pkg/core/operation.go [hunk 1]
```diff
@@ -74,6 +74,23 @@ func (op *Operation) IsTokenOperation() bool {
...
+		Status:      op.Status,
+		Plugin:      op.Plugin,
+		Input:       op.Input,
+		Output:      op.Output,
+		Error:       op.Error,
+		Created:     op.Created,
+		Updated:     op.Updated,
+		Retry:       op.Retry,
+	}
+}
```
Comment (EnriqueL8) [inline pkg/core/operation.go:92]: This DeepCopy needs to handle the fact that some of the fields are pointers so that they are deep copied correctly https://github.com/hyperledger/firefly/blob/74e2cbd38e688d0943618f149068880150a67020/pkg/core/operation.go#L114-L125 so needs a more sophisticated check for `nil` fields as well

Comment (EnriqueL8) [reply pkg/core/operation.go:92]: It works in your test because UUID is actually special in the case where it has no function to modify the value itself and in the test you are doing a complete replace

File: pkg/core/operation_test.go [hunk 2]
```diff
@@ -97,6 +98,45 @@ func TestOperationTypes(t *testing.T) {
...
+	assert.Equal(t, op.Updated, copyOp.Updated)
+	assert.Equal(t, op.Retry, copyOp.Retry)
+
+	// Ensure the copy is a deep copy
+	op.ID = fftypes.NewUUID()
+	assert.NotEqual(t, copyOp.ID, op.ID)
+
+	// Ensure no new fields are added to the Operation struct
+	// If a new field is added, this test will fail and the DeepCopy function should be updated
+	assert.Equal(t, 12, reflect.TypeOf(Operation{}).NumField())
```
Comment (EnriqueL8) [inline pkg/core/operation_test.go:138]: this is neat!

File: pkg/core/operation_test.go [hunk 3]
```diff
@@ -97,6 +98,45 @@ func TestOperationTypes(t *testing.T) {
...
+	assert.Equal(t, op.Input, copyOp.Input)
+	assert.Equal(t, op.Output, copyOp.Output)
+	assert.Equal(t, op.Error, copyOp.Error)
+	assert.Equal(t, op.Created, copyOp.Created)
+	assert.Equal(t, op.Updated, copyOp.Updated)
+	assert.Equal(t, op.Retry, copyOp.Retry)
+
+	// Ensure the copy is a deep copy
+	op.ID = fftypes.NewUUID()
+	assert.NotEqual(t, copyOp.ID, op.ID)
```
Comment (EnriqueL8) [inline pkg/core/operation_test.go:134]: can you add a test case with `fftypes.FFTime`

Comment (EnriqueL8) [inline pkg/core/operation_test.go:134]: This is not really proving what the function should do. You should really not reassign the field but instead compare the address of the returning fields `assert.NotEqual(t, &op.ID, &copyOp.ID)`

Your test is working because you copying the whole struct but not modifying the data of a field in place, because the `fftypes.UUID` and `fftypes.FFTime` do not have a mutating function we are "covered"

**Review by EnriqueL8 — APPROVED** [review]
LGTM - just needs that coverage bumped

**Review by EnriqueL8 — CHANGES_REQUESTED** [review]
just waiting on code coverage to be 100%

**Review by EnriqueL8 — APPROVED** [review]
LGTM
