### PR TITLE
Fix configuration dynamic reload logic

### LINKED ISSUE #1193: Dynamic reload causing Firefly to crash.
[2023-02-14T08:43:55.779Z] DEBUG FSEvent [CREATE] update=true: /etc/firefly/..2023_02_14_08_43_55.157763900 pid=1
[2023-02-14T08:43:55.780Z] INFO Config file change detected. Event=CREATE Name=/etc/firefly/firefly.core Size=2413 Hash=99c92cfc1173719ec4ef00dc91a397464373475ccb9f2d46dc0224b9d23ac0e4 pid=1
[2023-02-14T08:43:55.780Z] INFO Detected configuration file reload pid=1
[2023-02-14T08:43:55.787Z] ERROR Failed to re-read configuration after config reload notification: Unsupported Config Type "core" pid=1
[2023-02-14T08:43:55.787Z] INFO Shutting down due to cancelled context pid=1

### PR DESCRIPTION
**Pull request by Chengxuan**
fixes #1193

### CODE REVIEW

**Review by peterbroadhurst — APPROVED** [review]
Bunch of commentary.

One request before you merge - could you change the title of the PR to:
- Update config reload code to use the same filename resolution as startup

At the moment I think the title is misleading.

File: cmd/firefly.go [hunk 1]
```diff
@@ -153,7 +156,7 @@ func run() error {
 			<-ffDone
 			// Re-read the configuration
 			resetConfig()
-			if err = config.ReadConfig(configSuffix, cfgFile); err != nil {
+			if err = reloadConfig(); err != nil {
```
Comment (awrichar) [inline cmd/firefly.go:159]: Looks like you're calling `resetConfig` twice in a row along this path.
